PRAGMA defer_foreign_keys=TRUE;
INSERT INTO brands VALUES(1,'Acer','Acer is a global leader in computing, communications, and electronics technology. The company is known for its high-quality laptops, monitors, and innovative gadgets designed to enhance productivity and entertainment.','/media/acer.png','acer');
INSERT INTO brands VALUES(2,'Hisense','Hisense specializes in cutting-edge electronics and home appliances. With a focus on smart TVs and refrigeration, Hisense offers products that combine modern aesthetics with advanced technology.','/media/hisense.png','hisense');
INSERT INTO brands VALUES(3,'LG','LG Electronics is a household name for innovation, providing a wide range of home appliances, electronics, and mobile solutions that enrich everyday life.','/media/lg.png','lg');
INSERT INTO brands VALUES(4,'MI','MI, by Xiaomi, is synonymous with smart technology, offering a comprehensive lineup of smartphones, smart home devices, and lifestyle products that deliver excellent value and quality.','/media/mi.png','mi');
INSERT INTO brands VALUES(5,'Panasonic','Panasonic is committed to creating a better life and a better world through its comprehensive product range, which includes home electronics, kitchen appliances, and industrial solutions.','/media/panasonic.png','panasonic');
INSERT INTO brands VALUES(6,'Philips','Philips is a global leader in health technology and consumer electronics. From lighting solutions to personal care products, Philips focuses on innovations that make life easier and healthier.','/media/philips.png','philips');
INSERT INTO brands VALUES(7,'Samsung','Samsung is a world-renowned brand known for its cutting-edge smartphones, televisions, and appliances. It strives to push the boundaries of innovation to create products that improve daily life.','/media/samsung.png','samsung');
INSERT INTO brands VALUES(8,'Sony','Sony Corporation is a leader in entertainment and technology, offering high-quality electronics, gaming consoles, and imaging products that cater to a global audience.','/media/sony.png','sony');
INSERT INTO brands VALUES(9,'Toshiba','Toshiba is dedicated to creating technologies and products that enhance daily living, with a focus on electronics, energy solutions, and digital products.','/media/toshiba.png','toshiba');
INSERT INTO business_brand VALUES(1,1,1);
INSERT INTO business_brand VALUES(2,1,2);
INSERT INTO business_brand VALUES(3,1,3);
INSERT INTO business_brand VALUES(4,1,4);
INSERT INTO business_brand VALUES(5,1,5);
INSERT INTO business_brand VALUES(6,1,6);
INSERT INTO business_brand VALUES(7,1,7);
INSERT INTO business_brand VALUES(8,1,8);
INSERT INTO business_brand VALUES(9,1,9);
INSERT INTO business_brand VALUES(10,2,1);
INSERT INTO business_brand VALUES(11,2,2);
INSERT INTO business_brand VALUES(12,2,3);
INSERT INTO business_brand VALUES(13,2,4);
INSERT INTO business_brand VALUES(14,2,5);
INSERT INTO business_brand VALUES(15,2,6);
INSERT INTO business_brand VALUES(16,2,7);
INSERT INTO business_brand VALUES(17,2,8);
INSERT INTO business_brand VALUES(18,2,9);
INSERT INTO business_brand VALUES(19,3,1);
INSERT INTO business_brand VALUES(20,3,2);
INSERT INTO business_brand VALUES(21,3,3);
INSERT INTO business_brand VALUES(22,3,4);
INSERT INTO business_brand VALUES(23,3,5);
INSERT INTO business_brand VALUES(24,3,6);
INSERT INTO business_brand VALUES(25,3,7);
INSERT INTO business_brand VALUES(26,3,8);
INSERT INTO business_brand VALUES(27,3,9);
INSERT INTO business_brand VALUES(28,4,1);
INSERT INTO business_brand VALUES(29,4,2);
INSERT INTO business_brand VALUES(30,4,3);
INSERT INTO business_brand VALUES(31,4,4);
INSERT INTO business_brand VALUES(32,4,5);
INSERT INTO business_brand VALUES(33,4,6);
INSERT INTO business_brand VALUES(34,4,7);
INSERT INTO business_brand VALUES(35,4,8);
INSERT INTO business_brand VALUES(36,4,9);
INSERT INTO business_brand VALUES(37,5,1);
INSERT INTO business_brand VALUES(38,5,2);
INSERT INTO business_brand VALUES(39,5,3);
INSERT INTO business_brand VALUES(40,5,4);
INSERT INTO business_brand VALUES(41,5,5);
INSERT INTO business_brand VALUES(42,5,6);
INSERT INTO business_brand VALUES(43,5,7);
INSERT INTO business_brand VALUES(44,5,8);
INSERT INTO business_brand VALUES(45,5,9);
INSERT INTO business_product VALUES(1,1,7);
INSERT INTO business_product VALUES(2,1,1);
INSERT INTO business_product VALUES(3,1,2);
INSERT INTO business_product VALUES(4,1,4);
INSERT INTO business_product VALUES(5,1,6);
INSERT INTO business_product VALUES(6,1,3);
INSERT INTO business_product VALUES(7,1,5);
INSERT INTO business_product VALUES(8,2,7);
INSERT INTO business_product VALUES(9,2,1);
INSERT INTO business_product VALUES(10,2,2);
INSERT INTO business_product VALUES(11,2,4);
INSERT INTO business_product VALUES(12,2,6);
INSERT INTO business_product VALUES(13,2,3);
INSERT INTO business_product VALUES(14,2,5);
INSERT INTO business_product VALUES(15,3,7);
INSERT INTO business_product VALUES(16,3,1);
INSERT INTO business_product VALUES(17,3,2);
INSERT INTO business_product VALUES(18,3,4);
INSERT INTO business_product VALUES(19,3,6);
INSERT INTO business_product VALUES(20,3,3);
INSERT INTO business_product VALUES(21,3,5);
INSERT INTO business_product VALUES(22,4,7);
INSERT INTO business_product VALUES(23,4,1);
INSERT INTO business_product VALUES(24,4,2);
INSERT INTO business_product VALUES(25,4,4);
INSERT INTO business_product VALUES(26,4,6);
INSERT INTO business_product VALUES(27,4,3);
INSERT INTO business_product VALUES(28,4,5);
INSERT INTO business_product VALUES(29,5,7);
INSERT INTO business_product VALUES(30,5,1);
INSERT INTO business_product VALUES(31,5,2);
INSERT INTO business_product VALUES(32,5,4);
INSERT INTO business_product VALUES(33,5,6);
INSERT INTO business_product VALUES(34,5,3);
INSERT INTO business_product VALUES(35,5,5);
INSERT INTO businesses VALUES(1,'dealer','Acer Store','Acer Hub','https://maps.google.com/maps?q=31.7814258,76.9983784&hl=en&z=14&output=embed','123 Acer Street, New York, NY 10001','acer-store','/media/person.png',NULL);
INSERT INTO businesses VALUES(2,'dealer','Hisense Outlet','Hisense World','https://maps.google.com/maps?q=31.7814258,76.9983784&hl=en&z=14&output=embed','456 Hisense Avenue, Los Angeles, CA 90001','hisense-outlet','/media/person.png',NULL);
INSERT INTO businesses VALUES(3,'dealer','LG Showroom','LG Experience','https://maps.google.com/maps?q=31.7814258,76.9983784&hl=en&z=14&output=embed','789 LG Road, Chicago, IL 60601','lg-showroom','/media/person.png',NULL);
INSERT INTO businesses VALUES(4,'distributor','Samsung Plaza','Samsung Galaxy','https://maps.google.com/maps?q=31.7814258,76.9983784&hl=en&z=14&output=embed','101 Samsung Blvd, Houston, TX 77001','samsung-plaza','/media/person.png',NULL);
INSERT INTO businesses VALUES(5,'distributor','Sony Center','Sony Hub','https://maps.google.com/maps?q=31.7814258,76.9983784&hl=en&z=14&output=embed','202 Sony Lane, Seattle, WA 98101','sony-center','/media/person.png',NULL);
INSERT INTO contacts VALUES(1,1,'phone','+1-555-011');
INSERT INTO contacts VALUES(2,2,'phone','+1-555-012');
INSERT INTO contacts VALUES(3,3,'phone','+1-555-013');
INSERT INTO contacts VALUES(4,4,'phone','+1-555-014');
INSERT INTO contacts VALUES(5,5,'phone','+1-555-015');
INSERT INTO contacts VALUES(6,1,'email','contact1@business.com');
INSERT INTO contacts VALUES(7,2,'email','contact2@business.com');
INSERT INTO contacts VALUES(8,3,'email','contact3@business.com');
INSERT INTO contacts VALUES(9,4,'email','contact4@business.com');
INSERT INTO contacts VALUES(10,5,'email','contact5@business.com');
INSERT INTO contacts VALUES(11,1,'whatsapp','+1-555-021');
INSERT INTO contacts VALUES(12,2,'whatsapp','+1-555-022');
INSERT INTO contacts VALUES(13,3,'whatsapp','+1-555-023');
INSERT INTO contacts VALUES(14,4,'whatsapp','+1-555-024');
INSERT INTO contacts VALUES(15,5,'whatsapp','+1-555-025');
INSERT INTO contacts VALUES(16,1,'facebook','https://facebook.com/business1');
INSERT INTO contacts VALUES(17,2,'facebook','https://facebook.com/business2');
INSERT INTO contacts VALUES(18,3,'facebook','https://facebook.com/business3');
INSERT INTO contacts VALUES(19,4,'facebook','https://facebook.com/business4');
INSERT INTO contacts VALUES(20,5,'facebook','https://facebook.com/business5');
INSERT INTO contacts VALUES(21,1,'instagram','https://instagram.com/business1');
INSERT INTO contacts VALUES(22,2,'instagram','https://instagram.com/business2');
INSERT INTO contacts VALUES(23,3,'instagram','https://instagram.com/business3');
INSERT INTO contacts VALUES(24,4,'instagram','https://instagram.com/business4');
INSERT INTO contacts VALUES(25,5,'instagram','https://instagram.com/business5');
INSERT INTO product_brand VALUES(1,7,1);
INSERT INTO product_brand VALUES(2,7,2);
INSERT INTO product_brand VALUES(3,7,3);
INSERT INTO product_brand VALUES(4,7,4);
INSERT INTO product_brand VALUES(5,7,5);
INSERT INTO product_brand VALUES(6,7,6);
INSERT INTO product_brand VALUES(7,7,7);
INSERT INTO product_brand VALUES(8,7,8);
INSERT INTO product_brand VALUES(9,7,9);
INSERT INTO product_brand VALUES(10,1,1);
INSERT INTO product_brand VALUES(11,1,2);
INSERT INTO product_brand VALUES(12,1,3);
INSERT INTO product_brand VALUES(13,1,4);
INSERT INTO product_brand VALUES(14,1,5);
INSERT INTO product_brand VALUES(15,1,6);
INSERT INTO product_brand VALUES(16,1,7);
INSERT INTO product_brand VALUES(17,1,8);
INSERT INTO product_brand VALUES(18,1,9);
INSERT INTO product_brand VALUES(19,2,1);
INSERT INTO product_brand VALUES(20,2,2);
INSERT INTO product_brand VALUES(21,2,3);
INSERT INTO product_brand VALUES(22,2,4);
INSERT INTO product_brand VALUES(23,2,5);
INSERT INTO product_brand VALUES(24,2,6);
INSERT INTO product_brand VALUES(25,2,7);
INSERT INTO product_brand VALUES(26,2,8);
INSERT INTO product_brand VALUES(27,2,9);
INSERT INTO product_brand VALUES(28,4,1);
INSERT INTO product_brand VALUES(29,4,2);
INSERT INTO product_brand VALUES(30,4,3);
INSERT INTO product_brand VALUES(31,4,4);
INSERT INTO product_brand VALUES(32,4,5);
INSERT INTO product_brand VALUES(33,4,6);
INSERT INTO product_brand VALUES(34,4,7);
INSERT INTO product_brand VALUES(35,4,8);
INSERT INTO product_brand VALUES(36,4,9);
INSERT INTO product_brand VALUES(37,6,1);
INSERT INTO product_brand VALUES(38,6,2);
INSERT INTO product_brand VALUES(39,6,3);
INSERT INTO product_brand VALUES(40,6,4);
INSERT INTO product_brand VALUES(41,6,5);
INSERT INTO product_brand VALUES(42,6,6);
INSERT INTO product_brand VALUES(43,6,7);
INSERT INTO product_brand VALUES(44,6,8);
INSERT INTO product_brand VALUES(45,6,9);
INSERT INTO product_brand VALUES(46,3,1);
INSERT INTO product_brand VALUES(47,3,2);
INSERT INTO product_brand VALUES(48,3,3);
INSERT INTO product_brand VALUES(49,3,4);
INSERT INTO product_brand VALUES(50,3,5);
INSERT INTO product_brand VALUES(51,3,6);
INSERT INTO product_brand VALUES(52,3,7);
INSERT INTO product_brand VALUES(53,3,8);
INSERT INTO product_brand VALUES(54,3,9);
INSERT INTO product_brand VALUES(55,5,1);
INSERT INTO product_brand VALUES(56,5,2);
INSERT INTO product_brand VALUES(57,5,3);
INSERT INTO product_brand VALUES(58,5,4);
INSERT INTO product_brand VALUES(59,5,5);
INSERT INTO product_brand VALUES(60,5,6);
INSERT INTO product_brand VALUES(61,5,7);
INSERT INTO product_brand VALUES(62,5,8);
INSERT INTO product_brand VALUES(63,5,9);
INSERT INTO products VALUES(1,'Laptop','A laptop is a compact and portable personal computer equipped with the latest technology, perfect for work, study, or entertainment on the go.','/media/laptop.png','laptop');
INSERT INTO products VALUES(2,'PC','A desktop PC is a powerful and customizable personal computer designed for high performance and reliability, ideal for gaming, productivity, and creative work.','/media/pc.png','pc');
INSERT INTO products VALUES(3,'TV','Televisions are the centerpiece of home entertainment systems, offering high-resolution screens, smart capabilities, and immersive viewing experiences.','/media/tv.png','tv');
INSERT INTO products VALUES(4,'Phone','Smartphones are versatile devices that integrate communication, photography, and computing features into a single portable package, essential for modern life.','/media/phone.png','phone');
INSERT INTO products VALUES(5,'Webcam','Webcams are compact cameras designed for video conferencing, streaming, and online communication, providing crisp video quality for professional and personal use.','/media/webcam.png','webcam');
INSERT INTO products VALUES(6,'PS5','The Sony PlayStation 5 is a cutting-edge gaming console offering unparalleled graphics, speed, and immersive gameplay experiences for gamers worldwide.','/media/ps5.png','ps5');
INSERT INTO products VALUES(7,'Headphone','Headphones deliver high-quality sound for music, movies, and gaming. Designed for comfort and durability, they enhance every listening experience.','/media/headphone.png','headphone');
INSERT INTO sqlite_sequence VALUES('d1_migrations',2);
INSERT INTO sqlite_sequence VALUES('brands',9);
INSERT INTO sqlite_sequence VALUES('products',7);
INSERT INTO sqlite_sequence VALUES('businesses',5);
INSERT INTO sqlite_sequence VALUES('contacts',25);
INSERT INTO sqlite_sequence VALUES('business_product',35);
INSERT INTO sqlite_sequence VALUES('business_brand',45);
INSERT INTO sqlite_sequence VALUES('product_brand',63);